on:
  pull_request:
    types:
      - opened
    branches:
      - "18.0"

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --add-assignee lvessiller-opendsi,rycks --add-reviewer lvessiller-opendsi,rycks
          gh pr merge --auto
