on:
  pull_request:
    types:
      - opened
    branches:
      - "18.0"

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-assignee lvessiller-opendsi --add-reviewer lvessiller-opendsi
          gh pr merge "$url" --auto
